name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - name: GitConfig
        run: |
          git config --global --add safe.directory $(realpath .)
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: SetupGenpac
        run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x
         
          genpac --format=dnsmasq --dnsmasq-dns="127.0.0.1#53" --dnsmasq-ipset="ipset-name" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o dnsmasq.conf
          cat dnsmasq.conf |grep server= | awk -F "/" '{printf "forward-zone:\n  name: \"%s.\"\n  forward-addr: %s\n",$2,$3}' | sed 's/#/@/g' > unbound.conf
      
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
         
          git add dnsmasq.conf
          git add unbound.conf
          
          git commit -m "[$(LANG=C date)] auto update" || exit 0

          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

          git push origin main
